modLoader = "javafml"
loaderVersion = "[49,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/GrowthcraftCE/Growthcraft-Trapper/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-trapper-versions.json"
displayURL = "https://github.com/GrowthcraftCE/Growthcraft-Trapper/wiki"
logoFile = "growthcraft_trapper_logo.png"
credits = "Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
